# event_bus.yaml - 事件总线配置文件

# 基础配置
name: "FST_EVENT_BUS"
version: "1.3.0"

# 队列配置
queues:
  urgent:
    max_size: 1000
    overflow_policy: "drop_oldest"  # drop_oldest, drop_newest, block
  normal:
    max_size: 10000
    overflow_policy: "drop_oldest"
    batch_size: 100
    batch_timeout: 0.1  # 秒

# 线程池配置
worker_threads: 4
max_workers: 8

# QoS配置
qos:
  enabled: true
  target_latency: 0.1  # 秒
  max_batch_size: 1000
  min_batch_size: 10
  adaptive_interval: 1.0  # 秒

# 集群配置
cluster:
  enabled: false
  nodes: []
  heartbeat_interval: 5
  node_timeout: 15

# 监控配置
monitoring:
  prometheus:
    enabled: true
    port: 9090
  metrics:
    enabled: true
    collection_interval: 1.0  # 秒
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 验证配置
validation:
  enabled: true
  strict_mode: false
  schema_validation: true

# 过滤器配置
filters:
  enabled: true
  default_chain: ["type_check", "schema_check"]

# 路由配置
routing:
  enabled: true
  case_sensitive: false
  pattern_matching: "glob"  # glob, regex

# 记录器配置
recorder:
  enabled: true
  max_records: 10000
  compression_level: 6

# 性能优化
performance:
  use_uvloop: true
  zero_copy: true
  batch_processing: true
  compression: true

# 容错配置
fault_tolerance:
  circuit_breaker:
    enabled: true
    error_threshold: 50
    recovery_timeout: 30
  retry:
    enabled: true
    max_retries: 3
    backoff_factor: 2

# 安全配置
security:
  encryption:
    enabled: false
    algorithm: "AES-256"
  authentication:
    enabled: false
    method: "token"