# FST事件总线 - 生产环境配置

name: "FST_EVENT_BUS_PROD"
version: "1.3.0"

# 队列配置 - 生产环境使用较大的队列
queues:
  urgent:
    max_size: 2000
    overflow_policy: "block"  # 生产环境阻塞而不是丢弃
  normal:
    max_size: 20000
    overflow_policy: "block"
    batch_size: 200
    batch_timeout: 0.05  # 更短的超时以提高吞吐量

# 线程池配置 - 生产环境使用更多线程
worker_threads: 8
max_workers: 16

# QoS配置 - 生产环境严格的QoS要求
qos:
  enabled: true
  target_latency: 0.05  # 更严格的延迟要求
  max_batch_size: 1000
  min_batch_size: 50
  adaptive_interval: 0.5  # 更频繁的自适应调整

# 集群配置 - 生产环境启用集群
cluster:
  enabled: true
  nodes: ["node1:8001", "node2:8002", "node3:8003"]
  heartbeat_interval: 3
  node_timeout: 10

# 监控配置 - 生产环境完整监控
monitoring:
  prometheus:
    enabled: true
    port: 9090
  metrics:
    enabled: true
    collection_interval: 0.5  # 更频繁的指标收集
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/event_bus_prod.log"

# 验证配置 - 生产环境平衡验证
validation:
  enabled: true
  strict_mode: false  # 生产环境使用非严格模式
  schema_validation: true

# 过滤器配置
filters:
  enabled: true
  default_chain: ["type_check", "schema_check", "rate_limit"]

# 路由配置
routing:
  enabled: true
  case_sensitive: true  # 生产环境区分大小写
  pattern_matching: "regex"  # 使用正则以提高性能

# 记录器配置 - 生产环境平衡记录量
recorder:
  enabled: true
  max_records: 10000
  compression_level: 6  # 启用压缩

# 性能优化 - 生产环境启用所有优化
performance:
  use_uvloop: true
  zero_copy: true
  batch_processing: true
  compression: true

# 容错配置 - 生产环境严格的容错策略
fault_tolerance:
  circuit_breaker:
    enabled: true
    error_threshold: 30
    recovery_timeout: 60
  retry:
    enabled: true
    max_retries: 3
    backoff_factor: 2

# 安全配置 - 生产环境强制启用
security:
  encryption:
    enabled: true
    algorithm: "AES-256"
  authentication:
    enabled: true
    method: "token"