# FST事件总线 - 测试环境配置

name: "FST_EVENT_BUS_TEST"
version: "1.3.0"

# 队列配置 - 测试环境使用中等队列大小
queues:
  urgent:
    max_size: 1000
    overflow_policy: "drop_oldest"
  normal:
    max_size: 10000
    overflow_policy: "drop_oldest"
    batch_size: 100
    batch_timeout: 0.1

# 线程池配置 - 测试环境使用适中的线程数
worker_threads: 4
max_workers: 8

# QoS配置 - 测试环境使用适中的QoS设置
qos:
  enabled: true
  target_latency: 0.1
  max_batch_size: 500
  min_batch_size: 20
  adaptive_interval: 1.0

# 集群配置 - 测试环境可选择性启用集群
cluster:
  enabled: false  # 默认关闭，可根据测试需求开启
  nodes: ["test1:8001", "test2:8002"]
  heartbeat_interval: 5
  node_timeout: 15

# 监控配置 - 测试环境启用完整监控
monitoring:
  prometheus:
    enabled: true
    port: 9090
  metrics:
    enabled: true
    collection_interval: 1.0
  logging:
    level: "DEBUG"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/event_bus_test.log"

# 验证配置 - 测试环境启用完整验证
validation:
  enabled: true
  strict_mode: true
  schema_validation: true

# 过滤器配置
filters:
  enabled: true
  default_chain: ["type_check", "schema_check", "test_logger"]

# 路由配置
routing:
  enabled: true
  case_sensitive: false
  pattern_matching: "glob"

# 记录器配置 - 测试环境保留较多记录
recorder:
  enabled: true
  max_records: 15000
  compression_level: 0  # 测试环境不压缩

# 性能优化 - 测试环境可配置性启用
performance:
  use_uvloop: true
  zero_copy: false  # 便于调试
  batch_processing: true
  compression: false

# 容错配置 - 测试环境使用适中的容错策略
fault_tolerance:
  circuit_breaker:
    enabled: true
    error_threshold: 50
    recovery_timeout: 30
  retry:
    enabled: true
    max_retries: 3
    backoff_factor: 1.5

# 安全配置 - 测试环境可选择性启用
security:
  encryption:
    enabled: true
    algorithm: "AES-256"
  authentication:
    enabled: true
    method: "token"