# FST事件总线 - 开发环境配置

name: "FST_EVENT_BUS_DEV"
version: "1.3.0"

# 队列配置 - 开发环境使用较小的队列大小
queues:
  urgent:
    max_size: 500
    overflow_policy: "drop_oldest"
  normal:
    max_size: 5000
    overflow_policy: "drop_oldest"
    batch_size: 50
    batch_timeout: 0.2  # 较大的超时以便于调试

# 线程池配置 - 开发环境使用较少的线程
worker_threads: 2
max_workers: 4

# QoS配置 - 开发环境下放宽限制
qos:
  enabled: true
  target_latency: 0.2  # 较宽松的延迟要求
  max_batch_size: 500
  min_batch_size: 10
  adaptive_interval: 2.0  # 较长的自适应间隔

# 集群配置 - 开发环境通常不启用集群
cluster:
  enabled: false

# 监控配置 - 开发环境启用详细日志
monitoring:
  prometheus:
    enabled: true
    port: 9090
  metrics:
    enabled: true
    collection_interval: 1.0
  logging:
    level: "DEBUG"  # 开发环境使用DEBUG级别
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/event_bus_dev.log"

# 验证配置 - 开发环境启用严格验证
validation:
  enabled: true
  strict_mode: true  # 开发环境使用严格模式
  schema_validation: true

# 过滤器配置
filters:
  enabled: true
  default_chain: ["type_check", "schema_check", "debug_log"]

# 路由配置
routing:
  enabled: true
  case_sensitive: false
  pattern_matching: "glob"

# 记录器配置 - 开发环境保留更多记录
recorder:
  enabled: true
  max_records: 20000  # 更大的记录容量
  compression_level: 0  # 开发环境不压缩

# 性能优化 - 开发环境关闭部分优化
performance:
  use_uvloop: false  # 开发环境使用默认事件循环
  zero_copy: false
  batch_processing: true
  compression: false

# 容错配置 - 开发环境使用宽松的容错策略
fault_tolerance:
  circuit_breaker:
    enabled: true
    error_threshold: 100  # 更高的错误阈值
    recovery_timeout: 10
  retry:
    enabled: true
    max_retries: 5
    backoff_factor: 1

# 安全配置 - 开发环境可以禁用
security:
  encryption:
    enabled: false
  authentication:
    enabled: false